import { SinglePokemon } from '@/model/SinglePokemon'

// Get List of Pokemons

export interface Pokemon {
	count: number
	next: string
	previous: null
	results: Result[]
}

export interface Result {
	name: string
	url: string
}

export async function getPokemons(number: number): Promise<Pokemon> {
	const data = await fetch(
		`https://pokeapi.co/api/v2/pokemon?offset=${number * 20}&limit=20`,
		{ cache: 'default' }
	)
	const response = await data.json()
	return response
}

// Get Single pokemon

// Generated by https://quicktype.io

export async function getSinglePokemon(name: string): Promise<SinglePokemon> {
	const data = await fetch(`https://pokeapi.co/api/v2/pokemon/${name}`)
	const res = await data.json()
	return res
}

export async function getOnePoke(url: string): Promise<SinglePokemon> {
	const data = await fetch(url)
	const response = await data.json()
	return response
}

export async function getSerach(): Promise<Pokemon> {
	const data = await fetch(
		`https://pokeapi.co/api/v2/pokemon?offset=0&limit=1010`,
		{ cache: 'default' }
	)
	const response = await data.json()
	return response
}
